name: Retag build images

on: workflow_dispatch

env:
  DOCKER_CLI_EXPERIMENTAL: "enabled"

jobs:
  retag_linux:
    name: Retag all -tmp-master suffixes for Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - name: Retag all -tmp-master suffixes for Linux
        run: ./cl-docker-images-build/cl-docker-images-build pull_retag_and_push_linux_arch_images
